name: Build and Test on ubuntu-latest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run all tests
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
    - name: Exclude one test
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura --filter TestCategory!=TroubleMaker
